package Controller;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;
import javafx.scene.layout.HBox;

import java.io.IOException;
import java.net.URL;
import java.util.ResourceBundle;

import Modelo.Administrador;
import javafx.event.ActionEvent;

import javafx.scene.control.TabPane;

import javafx.scene.control.ToggleButton;
import javafx.scene.Parent;
import javafx.scene.control.Tab;
import javafx.scene.layout.AnchorPane;
import javafx.scene.layout.BorderPane;

import javafx.scene.control.TableView;
import javafx.scene.control.TextArea;
import javafx.scene.layout.GridPane;

import javafx.scene.layout.Pane;

import javafx.scene.control.TableColumn;

public class PainelAdmController implements Initializable{
	@FXML
	private Pane paneInicialAdm;
	@FXML
	private BorderPane bPanePainel;
	@FXML
	private GridPane gridStatusProc;
	@FXML
	private TableView tblStatusProc;
	@FXML
	private TableColumn colunStatusProc;
	@FXML
	private TabPane tblviewPrincipal;
	@FXML
	private Tab tabProcessos;
	@FXML
	private Tab tabCadastros;
	@FXML
	private AnchorPane aPaneProcessos;
	@FXML
	private AnchorPane aPaneCadastros;
	@FXML
	private GridPane gridUser;
	@FXML
	private HBox hbConfigSair;
	@FXML
	private ToggleButton btnConfig;
	@FXML
	private ToggleButton btnSair;
	@FXML
	private TextArea textUser;

	Administrador adm = new Administrador();

	@Override
	public void initialize(URL location, ResourceBundle resources) {
		//preencherMenus();
		textUser.setText(adm.getNome());
	}

	
	public void pegaAdm(Administrador adm){
		this.adm = adm;
	}

	@FXML
	public void abrirConfig(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ToggleButton[#btnSair].onAction
	@FXML
	public void deslogar(ActionEvent event) {
		// TODO Autogenerated
	}
	public void preencherMenus(){
		try {
			URL arquivoFXML,arquivoFXML2;
			arquivoFXML = getClass().getResource("/Visao/tabProcessos.fxml");
			Parent fxmlParent =(Parent) FXMLLoader.load(arquivoFXML);
			aPaneProcessos.getChildren().clear();
			aPaneProcessos.getChildren().add(fxmlParent);
			arquivoFXML2 = getClass().getResource("/Visao/tabCadastros.fxml");
			Parent fxmlParent2 =(Parent) FXMLLoader.load(arquivoFXML2);
			aPaneCadastros.getChildren().clear();
			aPaneCadastros.getChildren().add(fxmlParent2);
		} catch (Exception e) {
			e.getMessage();
		}

	}


}


