package Controller;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.layout.HBox;

import javafx.scene.control.TextField;

import javafx.scene.control.Label;

import javafx.scene.control.TextArea;

import javafx.scene.text.Text;

import javafx.scene.control.TreeTableColumn;

import javafx.scene.control.TreeTableView;

import javafx.scene.control.ToggleGroup;

import javafx.event.ActionEvent;

import javafx.scene.control.TabPane;

import javafx.scene.control.ComboBox;

import javafx.scene.control.ToggleButton;

import javafx.scene.layout.AnchorPane;

import javafx.scene.control.Tab;

import javafx.scene.control.RadioButton;

public class TabCadastrosController {
	@FXML
	private AnchorPane aPaneCadastro;
	@FXML
	private TabPane tabPaneCad;
	@FXML
	private Tab tabTipoProc;
	@FXML
	private AnchorPane aPaneTipoProc;
	@FXML
	private HBox hbDocumento;
	@FXML
	private ComboBox comboDocumentos;
	@FXML
	private ToggleButton btnAddDocTab;
	@FXML
	private Label lblDescricao;
	@FXML
	private HBox hbCrudProc;
	@FXML
	private Button btnExcluirProc;
	@FXML
	private Button btnAlterarProc;
	@FXML
	private Button btnSalvarProc;
	@FXML
	private TreeTableView tblFluxoProc;
	@FXML
	private TreeTableColumn colunFluxo;
	@FXML
	private TreeTableView tblDocumentos;
	@FXML
	private TreeTableColumn colunDocumentos;
	@FXML
	private Label lblNomeProc;
	@FXML
	private Label lblBuscaResponsavel;
	@FXML
	private HBox hbBuscaResp;
	@FXML
	private TextField txtBuscResp;
	@FXML
	private ToggleButton btnAddResp;
	@FXML
	private TextField txtNomeProc;
	@FXML
	private Label lblDocumento;
	@FXML
	private Text textCadTipoProc;
	@FXML
	private TextArea txtDescricao;
	@FXML
	private Label txtBuscaProc;
	@FXML
	private ComboBox comboTiposProc;
	@FXML
	private Tab tabUsuario;
	@FXML
	private AnchorPane aPaneUser;
	@FXML
	private Label lblNome;
	@FXML
	private Label lblCpf;
	@FXML
	private Label lblCargo;
	@FXML
	private ComboBox comoTipoUser;
	@FXML
	private TextField txtTelefone;
	@FXML
	private HBox hbSexo;
	@FXML
	private RadioButton rbMasculino;
	@FXML
	private ToggleGroup groupSexo;
	@FXML
	private RadioButton rbFeminino;
	@FXML
	private TextField txtMatricula;
	@FXML
	private Label lblSexo;
	@FXML
	private Label lblMatricula;
	@FXML
	private TextField txtEmail;
	@FXML
	private Label lblTipoUser;
	@FXML
	private ComboBox comboCargo;
	@FXML
	private HBox hbCrud;
	@FXML
	private Button btnAlterarUser;
	@FXML
	private Button btnSalvarUser;
	@FXML
	private Label lblDepart;
	@FXML
	private Label lblTelefone;
	@FXML
	private TextField txtCpf;
	@FXML
	private ComboBox comoDepart;
	@FXML
	private TextField txtNome;
	@FXML
	private Label lblEmail;
	@FXML
	private Text textCadUser;
	@FXML
	private Label lblBuscaUser;
	@FXML
	private TextField txtBuscaUser;
	@FXML
	private ToggleButton btnBuscaUser;
	@FXML
	private ComboBox comboTipoBuscaUser;
	@FXML
	private Tab tabDocumentos;
	@FXML
	private AnchorPane aPaneDoc;
	@FXML
	private Label lblNomeDoc;
	@FXML
	private TextField txtNomeDoc;
	@FXML
	private TreeTableView tblListDocumentos;
	@FXML
	private TreeTableColumn colunListDocumentos;
	@FXML
	private HBox hbCrudDoc;
	@FXML
	private Button btnExcluirDoc;
	@FXML
	private Button btnAlterarDoc;
	@FXML
	private Button btnSalvarDoc;
	@FXML
	private ToggleButton btnAddDoc;

	// Event Listener on ToggleButton[#btnAddDocTab].onAction
	@FXML
	public void addDocumentoTabela(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnExcluirProc].onAction
	@FXML
	public void excluirProcesso(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnAlterarProc].onAction
	@FXML
	public void editarProcesso(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnSalvarProc].onAction
	@FXML
	public void salvarProcesso(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ToggleButton[#btnAddResp].onAction
	@FXML
	public void addResponsavelFluxo(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnAlterarUser].onAction
	@FXML
	public void editarUsuario(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnSalvarUser].onAction
	@FXML
	public void salvarUsuario(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ToggleButton[#btnBuscaUser].onAction
	@FXML
	public void buscarUsuarios(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnExcluirDoc].onAction
	@FXML
	public void excluirDocumentosList(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnAlterarDoc].onAction
	@FXML
	public void editarDocumentoList(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnSalvarDoc].onAction
	@FXML
	public void salvarDocumentoList(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ToggleButton[#btnAddDoc].onAction
	@FXML
	public void addDocumentoLista(ActionEvent event) {
		// TODO Autogenerated
	}
}
