package Controller;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.text.Text;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import java.util.ResourceBundle;

import Dao.ProcessosDao;
import Modelo.Processo;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;

import javafx.scene.control.ComboBox;

import javafx.scene.control.ToggleButton;
import javafx.scene.control.cell.PropertyValueFactory;
import javafx.scene.control.TableView;
import javafx.scene.layout.AnchorPane;
import javafx.scene.layout.Pane;

import javafx.scene.control.TableColumn;

public class TabConsultaProcController implements Initializable{
	
	@FXML
	private AnchorPane aPaneConsulProc;
	@FXML
	private Text textBuscarProcAberto;
	@FXML
	private Pane paneProcesso;
	@FXML
	private TableView<Processo> tblProcAbertos;
	@FXML
	private TableColumn<Processo,Integer> colunProtBusc;
	@FXML
	private TableColumn<Processo,String> colunBuscNomeProc;
	@FXML
	private TableColumn<Processo,String>  colunBuscNomeAlu;
	@FXML
	private TableColumn<Processo,String>  colunBuscStatus;
	@FXML
	private Button btnCacelBusc;
	@FXML
	private TextField txtBuscarProcAberto;
	@FXML
	private ComboBox comboTipoPesqui;
	@FXML
	private ToggleButton btnBuscarProcAberto;
	
	
	ProcessosDao proDao = new ProcessosDao();
	List<Processo> listPro = new ArrayList<Processo>();
	ObservableList<Processo> proView;
	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		preencherTipoPesq();
		populaProView();
		
	}
	@FXML
	public void preencherTipoPesq(){
		List<String> list = new ArrayList<>();
		list.add("Protocolo");
		list.add("Nome");
		list.add("Aluno");
		comboTipoPesqui.getItems().addAll(list);
	}

	public void populaProView(){
		listPro = proDao.listarProc();
		
		colunProtBusc.setCellValueFactory(new PropertyValueFactory<Processo, Integer>("id"));
		colunBuscNomeProc.setCellValueFactory(new PropertyValueFactory<Processo, String>("Nome"));
		colunBuscNomeAlu.setCellValueFactory(new PropertyValueFactory<Processo, String>("alunoNome"));
		colunBuscStatus.setCellValueFactory(new PropertyValueFactory<Processo, String>("status"));
		proView = FXCollections.observableArrayList(listPro);
		tblProcAbertos.getItems().removeAll();
		tblProcAbertos.setItems(proView);
	}
	// Event Listener on Button[#btnCacelBusc].onAction
	@FXML
	public void cancelarBusca(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ToggleButton[#btnBuscarProcAberto].onAction
	@FXML
	public void buscarProcessoAberto(ActionEvent event) {
		// TODO Autogenerated
	}

	
}
