package Controller;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.text.Text;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import java.util.ResourceBundle;

import javafx.event.ActionEvent;

import javafx.scene.control.ComboBox;

import javafx.scene.control.ToggleButton;

import javafx.scene.control.TableView;
import javafx.scene.layout.AnchorPane;
import javafx.scene.layout.Pane;

import javafx.scene.control.TableColumn;

public class TabConsultaProcController implements Initializable{
	
	@FXML
	private AnchorPane aPaneConsulProc;
	@FXML
	private Text textBuscarProcAberto;
	@FXML
	private Pane paneProcesso;
	@FXML
	private TableView tblProcAbertos;
	@FXML
	private TableColumn colunProtBusc;
	@FXML
	private TableColumn colunBuscNomeProc;
	@FXML
	private TableColumn colunBuscNomeAlu;
	@FXML
	private TableColumn colunBuscStatus;
	@FXML
	private Button btnCacelBusc;
	@FXML
	private TextField txtBuscarProcAberto;
	@FXML
	private ComboBox comboTipoPesqui;
	@FXML
	private ToggleButton btnBuscarProcAberto;
	
	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		preencherTipoPesq();
		
	}
	@FXML
	public void preencherTipoPesq(){
		List<String> list = new ArrayList<>();
		list.add("Protocolo");
		list.add("Nome");
		list.add("Aluno");
		comboTipoPesqui.getItems().addAll(list);
	}

	// Event Listener on Button[#btnCacelBusc].onAction
	@FXML
	public void cancelarBusca(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ToggleButton[#btnBuscarProcAberto].onAction
	@FXML
	public void buscarProcessoAberto(ActionEvent event) {
		// TODO Autogenerated
	}

	
}
