package Controller;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.text.Text;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

import javafx.scene.control.TabPane;

import javafx.scene.control.ComboBox;

import javafx.scene.control.ToggleButton;

import javafx.scene.layout.AnchorPane;

import javafx.scene.control.Tab;

import javafx.scene.control.TableView;

import javafx.scene.control.TableColumn;

import javafx.scene.layout.Pane;

public class TabProcessosController {
	@FXML
	private AnchorPane aPaneProcesso;
	@FXML
	private TabPane tabPaneProcessos;
	@FXML
	private Tab tabAbrirNovoProc;
	@FXML
	private AnchorPane aPaneAbrirPro;
	@FXML
	private TextField txtPesqAluno;
	@FXML
	private ComboBox comboTipoPesquiAluno;
	@FXML
	private Button btnAbrirAlunoView;
	@FXML
	private ToggleButton btnBuscar;
	@FXML
	private TableView tabAlunosPorbusca;
	@FXML
	private TableColumn colunMatric;
	@FXML
	private TableColumn colunNome;
	@FXML
	private TableColumn colunCpf;
	@FXML
	private Text textProcAberto1;
	@FXML
	private Tab tabProcPendente;
	@FXML
	private AnchorPane aPaneProcPendente;
	@FXML
	private Text textProcAberto;
	@FXML
	private Pane panePendentes;
	@FXML
	private TableView tblProcPendente;
	@FXML
	private TableColumn colunPendProtoc;
	@FXML
	private TableColumn colunPendNomeProc;
	@FXML
	private TableColumn colunPendNomeAlu;
	@FXML
	private TextField txtBuscarProc;
	@FXML
	private Button btnAbrirProcView;
	@FXML
	private ToggleButton btnBuscarProcPendente;
	@FXML
	private Tab tabBuscarProc;
	@FXML
	private AnchorPane aPaneBuscarProc;
	@FXML
	private Text textBuscarProcAberto;
	@FXML
	private TextField txtBuscarProcAberto;
	@FXML
	private ComboBox comboTipoPesqui;
	@FXML
	private Pane paneProcesso;
	@FXML
	private TableView tblProcAbertos;
	@FXML
	private TableColumn colunProtBusc;
	@FXML
	private TableColumn colunBuscNomeProc;
	@FXML
	private TableColumn colunBuscNomeAlu;
	@FXML
	private TableColumn colunBuscStatus;
	@FXML
	private Button btnCacelBusc;
	@FXML
	private ToggleButton btnBuscarProcAberto;

	// Event Listener on Button[#btnAbrirAlunoView].onAction
	@FXML
	public void abrirViewAluno(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ToggleButton[#btnBuscar].onAction
	@FXML
	public void buscarAluno(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnAbrirProcView].onAction
	@FXML
	public void abrirProcView(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ToggleButton[#btnBuscarProcPendente].onAction
	@FXML
	public void buscarProcessoPendente(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnCacelBusc].onAction
	@FXML
	public void cancelarBusca(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ToggleButton[#btnBuscarProcAberto].onAction
	@FXML
	public void buscarProcessoAberto(ActionEvent event) {
		// TODO Autogenerated
	}
}
