package Controller;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;

import javafx.scene.layout.HBox;

import javafx.scene.control.TextField;

import javafx.scene.control.Label;

import javafx.scene.text.Text;

import javafx.scene.control.ToggleGroup;

import java.net.URL;
import java.util.ResourceBundle;

import javafx.event.ActionEvent;

import javafx.scene.control.TabPane;

import javafx.scene.control.ComboBox;

import javafx.scene.control.ToggleButton;

import javafx.scene.layout.AnchorPane;

import javafx.scene.control.Tab;

import javafx.scene.control.RadioButton;

import javafx.scene.control.DatePicker;

import javafx.scene.control.TableView;

import javafx.scene.layout.Pane;

public class TabProcessosController implements Initializable {
	@FXML
	private AnchorPane aPaneProcesso;
	@FXML
	private TabPane tabPaneProcessos;
	@FXML
	private Tab tabAbrirNovoProc;
	@FXML
	private AnchorPane aPaneAbrirPro;
	@FXML
	private Label lblPesquiAluno;
	@FXML
	private TextField txtPesqAluno;
	@FXML
	private ComboBox comboTipoPesquiAluno;
	@FXML
	private Label lblBairo;
	@FXML
	private Label lblCpf;
	@FXML
	private TextField txtNome;
	@FXML
	private Label lblMatricula;
	@FXML
	private Label lblResponsavel;
	@FXML
	private Label lblEmail;
	@FXML
	private Label lblSexo;
	@FXML
	private TextField txtMatricula;
	@FXML
	private Label lblCurso;
	@FXML
	private DatePicker dateDataNasc;
	@FXML
	private Label lblTelefone;
	@FXML
	private Label lblDataNasc;
	@FXML
	private TextField txtEndereco;
	@FXML
	private TextField txtBairro;
	@FXML
	private TextField txtResponsavel;
	@FXML
	private TextField txtEmail;
	@FXML
	private TextField txtTelefone;
	@FXML
	private TextField txtCpf;
	@FXML
	private TextField txtCurso;
	@FXML
	private Label lblEnderco;
	@FXML
	private HBox hbCrud;
	@FXML
	private Button btnExcluir;
	@FXML
	private Button btnAlterar;
	@FXML
	private Button btnSalvar;
	@FXML
	private HBox hbSexo;
	@FXML
	private RadioButton rbMasculino;
	@FXML
	private ToggleGroup groupSexo;
	@FXML
	private RadioButton rbFeminino;
	@FXML
	private Label lblNome;
	@FXML
	private Button btnAbrirProc;
	@FXML
	private ToggleButton btnBuscar;
	@FXML
	private Tab tabProcPendente;
	@FXML
	private AnchorPane aPaneProcPendente;
	@FXML
	private TableView tblProcPendente;
	@FXML
	private Text textProcAberto;
	@FXML
	private Button btnAbrir;
	@FXML
	private Label lblBuscarProcesso;
	@FXML
	private TextField txtBuscarProc;
	@FXML
	private ToggleButton btnBuscarProcPendente;
	@FXML
	private Tab tabBuscarProc;
	@FXML
	private AnchorPane aPaneBuscarProc;
	@FXML
	private Text textBuscarProcAberto;
	@FXML
	private TextField txtBuscarProcAberto;
	@FXML
	private ComboBox comboTipoPesqui;
	@FXML
	private Label lblPesquisarPor;
	@FXML
	private Pane paneProcesso;
	@FXML
	private ToggleButton btnBuscarProcAberto;
	
	
	
	@Override
	public void initialize(URL location, ResourceBundle resources) {
		
	}
	

	// Event Listener on Button[#btnExcluir].onAction
	@FXML
	public void excluirProcesso(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnAlterar].onAction
	@FXML
	public void editarProcesso(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnSalvar].onAction
	@FXML
	public void salvarProcesso(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnAbrirProc].onAction
	@FXML
	public void abrirNovoProcesso(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ToggleButton[#btnBuscar].onAction
	@FXML
	public void buscarAluno(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnAbrir].onAction
	@FXML
	public void abrirProcesso(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ToggleButton[#btnBuscarProcPendente].onAction
	@FXML
	public void buscarProcessoPendente(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ToggleButton[#btnBuscarProcAberto].onAction
	@FXML
	public void buscarProcessoAberto(ActionEvent event) {
		// TODO Autogenerated
	}
	
}
