package Controller;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;
import javafx.scene.Parent;
import javafx.scene.control.Button;

import javafx.scene.layout.HBox;

import javafx.scene.control.TextField;

import javafx.scene.control.ToggleGroup;
import javafx.scene.control.cell.PropertyValueFactory;

import java.io.IOException;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import java.util.ResourceBundle;

import com.mysql.fabric.xmlrpc.base.Data;

import Dao.ProcessosDao;
import Modelo.Aluno;
import Modelo.Processo;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;

import javafx.scene.control.ToggleButton;

import javafx.scene.layout.AnchorPane;

import javafx.scene.control.RadioButton;

import javafx.scene.control.DatePicker;

import javafx.scene.control.TableView;

import javafx.scene.layout.Pane;

import javafx.scene.control.TableColumn;

public class TelaDadosAlunoController implements Initializable{
	@FXML
	private AnchorPane aPaneTelaDadosAlun;
	@FXML
	private Pane paneDadosAluno;
	@FXML
	private TextField txtResponsavel;
	@FXML
	private TextField txtEndereco;
	@FXML
	private TextField txtCpf;
	@FXML
	private HBox hbCrud;
	@FXML
	private Button btnAlterar;
	@FXML
	private Button btnSalvar;
	@FXML
	private TextField txtCurso;
	@FXML
	private DatePicker dateDataNasc;
	@FXML
	private TextField txtCity;
	@FXML
	private HBox hbSexo;
	@FXML
	private RadioButton rbMasculino;
	@FXML
	private ToggleGroup groupSexo;
	@FXML
	private RadioButton rbFeminino;
	@FXML
	private TextField txtNome;
	@FXML
	private TextField txtTelefone;
	@FXML
	private TextField txtMatricula;
	@FXML
	private TextField txtEmail;
	@FXML
	private HBox hbAbrirCancel;
	@FXML
	private Button btnCancelar;
	@FXML
	private Button btnAbrirNovoPoc;
	@FXML
	private TableView<Processo> tabProceAluno;
	@FXML
	private TableColumn<Processo,Integer> colunProtocologo;
	@FXML
	private TableColumn<Processo,String> colunNome;
	@FXML
	private TableColumn<Processo,String> colunStatus;


	static Aluno alu = new Aluno();
	TelaNewProcessoController newProc = new TelaNewProcessoController();
	ProcessosDao proDao = new ProcessosDao();
	ObservableList<Processo> proView = null;
	

	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		setarAluno();
		populaProcessos();
		

	}
	public void recuperarAluno(Aluno alu){
		this.alu=alu;
	}
	@FXML
	public void setarAluno(){
		txtNome.setText(alu.getNome());
		txtCity.setText(alu.getCity());
		txtCpf.setText(alu.getCpf());
		txtCurso.setText(alu.getCurso());
		txtEmail.setText(alu.getEmail());
		txtEndereco.setText(alu.getEnder());
		txtMatricula.setText(alu.getMatricula());
		txtResponsavel.setText(alu.getResponsavel());
		txtTelefone.setText(alu.getTelefone());
		if(alu.getSexo().equals("Masculino")){
			rbMasculino.setSelected(true);
			rbFeminino.setDisable(true);
		}else{
			if(alu.getSexo().equals("Feminino")){
				rbFeminino.setSelected(true);
				rbMasculino.setDisable(true);
			}
		}
		dateDataNasc.setValue(alu.getDataNasci());

	}
	@FXML
	public void abrirNovoProcesso(ActionEvent event) throws Exception {

		newProc.recuperarAluno(alu);
		URL arquivoFXML;
		arquivoFXML = getClass().getResource("/Visao/telaNewProcesso.fxml");
		Parent fxmlParent =(Parent) FXMLLoader.load(arquivoFXML);
		paneDadosAluno.getChildren().clear();
		paneDadosAluno.getChildren().add(fxmlParent);
	}


	@FXML
	public void editarProcesso(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnSalvar].onAction
	@FXML
	public void salvarProcesso(ActionEvent event) {
		// TODO Autogenerated
	}

	@FXML
	public void cancelarTudo(ActionEvent event) throws Exception {
		URL arquivoFXML;
		arquivoFXML = getClass().getResource("/Visao/tabAbrirNovoProc.fxml");
		Parent fxmlParent = null;
		fxmlParent = (Parent) FXMLLoader.load(arquivoFXML);
		aPaneTelaDadosAlun.getChildren().clear();
		aPaneTelaDadosAlun.getChildren().add(fxmlParent);
	}
	public void populaProcessos(){
		List<Processo> listPro = new ArrayList<>();

		listPro = proDao.listarProcProAluno(alu);
		if(!listPro.isEmpty()){
			colunProtocologo.setCellValueFactory(new PropertyValueFactory<Processo, Integer>("id"));
			colunNome.setCellValueFactory(new PropertyValueFactory<Processo, String>("Nome"));
			colunStatus.setCellValueFactory(new PropertyValueFactory<Processo, String>("Status"));
			proView = FXCollections.observableArrayList(listPro);
			tabProceAluno.getItems().removeAll();
			tabProceAluno.setItems(proView);
		}
	}

}
