package Controller;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;

import javafx.scene.layout.HBox;

import java.net.URL;
import java.util.ResourceBundle;

import Modelo.Aluno;
import javafx.event.ActionEvent;

import javafx.scene.layout.AnchorPane;

import javafx.scene.control.TableView;

import javafx.scene.layout.Pane;

import javafx.scene.control.TableColumn;

public class TelaProcessoController implements Initializable {
	@FXML
	private Pane paneProcesso;
	@FXML
	private AnchorPane ApaneTabela;
	@FXML
	private HBox hbCrud;
	@FXML
	private Button btnExcluir;
	@FXML
	private Button btnAlterar;
	@FXML
	private Button btnSalvar;
	@FXML
	private HBox hbResposta;
	@FXML
	private Button btnIndeferir;
	@FXML
	private Button btnDeferir;
	@FXML
	private TableView tblProcessosView;
	@FXML
	private TableColumn colunProcesso;
	@FXML
	private TableColumn colunStatus;
	@FXML
	private TableColumn colunComent;

	static Aluno alu = new Aluno();
	
	
	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
	
	}
	
	public void recuperarAluno(Aluno alu){
		this.alu=alu;
	}
	@FXML
	public void excluirProcesso(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnAlterar].onAction
	@FXML
	public void editarProcesso(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnSalvar].onAction
	@FXML
	public void salvarProcesso(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnIndeferir].onAction
	@FXML
	public void indeferirProc(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnDeferir].onAction
	@FXML
	public void deferirProc(ActionEvent event) {
		// TODO Autogenerated
	}
	
}
